import localFont from 'next/font/local'
import './globals.css'
import Link from 'next/link'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900 flex flex-col justify-between min-h-screen">
        <header className="p-4 bg-indigo-900 text-white text-center">
          <Link href={'/'}>
            <h1>Car Dealer App</h1>
          </Link>
        </header>
        <main className="bg-indigo-100 p-3 lg:p-6 flex-1">{children}</main>
        <footer className="p-2 bg-indigo-950 text-white text-center">
          2024, Yevhenii Yeremenko
        </footer>
      </body>
    </html>
  )
}
